// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function DoUpdate(arg1:string):Promise<void>;

export function GetVersion():Promise<string>;

export function HideWindow():Promise<void>;

export function Quit():Promise<void>;

export function SetHost(arg1:string):Promise<void>;

export function UpdateTrayTitle(arg1:string):Promise<void>;
