// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideWindow():Promise<void>;

export function Quit():Promise<void>;

export function SetHost(arg1:string):Promise<void>;

export function UpdateTrayTitle(arg1:string):Promise<void>;
