// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DoUpdate(arg1) {
  return window['go']['main']['App']['DoUpdate'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetHost(arg1) {
  return window['go']['main']['App']['SetHost'](arg1);
}

export function UpdateTrayTitle(arg1) {
  return window['go']['main']['App']['UpdateTrayTitle'](arg1);
}
